#pragma once
// GENERATED by tools/gen_anim_list.py - do not edit by hand.
//
// Asset names, so these are the same on every build and platform. An entry the
// build does not have simply fails to stream and the animation does not play.

struct anim_entry  { const char* name; const char* dict; const char* anim; };
struct named_entry { const char* name; const char* id; };
struct anim_group  { const char* name; const anim_entry*  items; int count; };
struct named_group { const char* name; const named_entry* items; int count; };

static const anim_entry animation_sexual[] = {
    { "Doggystyle 1", "rcmpaparazzo_2", "shag_loop_poppy" },
    { "Doggystyle 2", "rcmpaparazzo_2", "shag_loop_a" },
    { "Shaking Ass", "switch@trevor@mocks_lapdance", "001443_01_trvs_28_idle_stripper" },
    { "Slow Humping", "misscarsteal2pimpsex", "shagloop_pimp" },
};

static const anim_entry animation_animals[] = {
    { "Monkey", "missfbi5ig_30monkeys", "monkey_b_freakout_loop" },
    { "Chop Hump", "missfra0_chop_find", "hump_loop_chop" },
    { "Chop Swim", "creatures@rottweiler@swim@", "swim" },
};

static const anim_entry animation_actions[] = {
    { "Air Guitar", "anim@mp_player_intcelebrationfemale@air_guitar", "air_guitar" },
    { "Blow Kiss", "anim@mp_player_intcelebrationfemale@blow_kiss", "blow_kiss" },
    { "Bro Hug", "anim@mp_player_intcelebrationpaired@f_m_bro_hug", "bro_hug_right" },
    { "Challenge", "misscommon@response", "face_palm" },
    { "Face Palm", "anim@mp_player_intcelebrationmale@face_palm", "" },
    { "Finger", "anim@mp_player_intcelebrationmale@finger", "finger" },
    { "Hands Up", "mp_pol_bust_out", "guard_handsup_loop" },
    { "Hump Air", "anim@mp_player_intcelebrationfemale@air_shagging", "air_shagging" },
    { "Jazz Hands", "anim@mp_player_intcelebrationmale@jazz_hands", "jazz_hands" },
    { "Nose Pick", "anim@mp_player_intcelebrationmale@nose_pick", "nose_pick" },
    { "Photographer", "anim@mp_player_intcelebrationmale@photography", "photography" },
    { "Salute", "anim@mp_player_intcelebrationmale@salute", "salute" },
    { "Shush", "anim@mp_player_intcelebrationmale@shush", "shush" },
    { "Slow Clap", "anim@mp_player_intcelebrationmale@slow_clap", "slow_clap" },
    { "Smoke", "anim@mp_player_intcelebrationmale@smoke_flick", "smoke_flick" },
    { "Surrender", "anim@mp_player_intcelebrationmale@surrender", "surrender" },
    { "Synth", "anim@mp_player_intcelebrationfemale@air_synth", "air_synth" },
    { "Thumbs Up", "anim@mp_player_intcelebrationmale@thumbs_up", "thumbs_up" },
    { "Wank", "mp_player_intwank", "mp_player_int_wank" },
};

static const anim_entry animation_dance[] = {
    { "Casual", "rcmnigel1bnmt_1b", "dance_loop_tyler" },
    { "Clown", "rcm_barry2", "clown_idle_6" },
    { "Pole", "mini@strip_club@pole_dance@pole_dance3", "pd_dance_03" },
    { "Private", "mini@strip_club@private_dance@part2", "priv_dance_p2" },
    { "Receive", "mp_am_stripper", "lap_dance_player" },
    { "Sexual", "mini@strip_club@pole_dance@pole_a_2_stage", "pole_a_2_stage" },
    { "Yacht", "oddjobs@assassinate@multi@yachttarget@lapdance", "yacht_ld_f" },
};

static const anim_entry animation_misc[] = {
    { "Electrocute", "ragdoll@human", "electrocute" },
    { "Hover", "swimming@base", "dive_idle" },
    { "Jump", "move_jump", "jump_launch_l_to_skydive" },
    { "Meditate", "rcmcollect_paperleadinout@", "meditiate_idle" },
    { "Party", "rcmfanatic1celebrate", "celebrate" },
    { "Pissing", "misscarsteal2peeing", "peeing_loop" },
    { "Push Ups", "rcmfanatic3", "ef_3_rcm_loop_maryann" },
    { "Run", "move_m@alien", "alien_run" },
    { "Shitting", "missfbi3ig_0", "shit_loop_trev" },
    { "Showering", "mp_safehouseshower@male@", "male_shower_idle_b" },
    { "Swim", "swimming@scuba", "dive_idle" },
    { "Vomit", "missfam5_blackout", "vomit" },
    { "Wave Forward", "friends@frj@ig_1", "wave_d" },
    { "Wave Hands High", "random@prisoner_lift", "arms_waving" },
    { "Wave One Arm", "random@shop_gunstore", "_greeting" },
};

static const anim_group animation_groups[] = {
    { "Sexual", animation_sexual, 4 },
    { "Animals", animation_animals, 3 },
    { "Actions", animation_actions, 19 },
    { "Dance", animation_dance, 7 },
    { "Misc", animation_misc, 15 },
};
static const int animation_group_count = 5;

static const named_entry scenario_ambient[] = {
    { "Coffee", "WORLD_HUMAN_AA_COFFEE" },
    { "Smoking", "WORLD_HUMAN_AA_SMOKE" },
    { "Freeway Bum", "WORLD_HUMAN_BUM_FREEWAY" },
    { "Sleeping Bum", "WORLD_HUMAN_BUM_SLUMPED" },
    { "Cheer", "WORLD_HUMAN_CHEERING" },
    { "Partying", "WORLD_HUMAN_PARTYING" },
    { "Shine Flashlight", "WORLD_HUMAN_SECURITY_SHINE_TORCH" },
    { "Tourist Map", "WORLD_HUMAN_TOURIST_MAP" },
};

static const named_entry scenario_activities[] = {
    { "Binoculars", "WORLD_HUMAN_BINOCULARS" },
    { "Drunk", "WORLD_HUMAN_DRINKING" },
    { "Human Statue", "WORLD_HUMAN_HUMAN_STATUE" },
    { "Musician", "WORLD_HUMAN_MUSICIAN" },
    { "Fishing", "WORLD_HUMAN_STAND_FISHING" },
    { "BBQ", "PROP_HUMAN_BBQ" },
    { "Yoga", "WORLD_HUMAN_YOGA" },
};

static const named_entry scenario_animals[] = {
    { "Grazing Boar", "WORLD_BOAR_GRAZING" },
    { "Grazing Cow", "WORLD_COW_GRAZING" },
    { "Coyote Howl", "WORLD_COYOTE_HOWL" },
    { "Coyote Rest", "WORLD_COYOTE_REST" },
    { "Coyote Wander", "WORLD_COYOTE_WANDER" },
    { "Rottweiler Bark", "WORLD_DOG_BARKING_ROTTWEILER" },
};

static const named_entry scenario_fitness[] = {
    { "Idle Jogger", "WORLD_HUMAN_JOG_STANDING" },
    { "Golf", "WORLD_HUMAN_GOLF_PLAYER" },
    { "Muscle Flex", "WORLD_HUMAN_MUSCLE_FLEX" },
    { "Free Weights", "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS" },
    { "Tennis", "WORLD_HUMAN_TENNIS_PLAYER" },
    { "Bench Press", "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS" },
};

static const named_entry scenario_industrial[] = {
    { "Parking Attendant", "WORLD_HUMAN_CAR_PARK_ATTENDANT" },
    { "Drill", "WORLD_HUMAN_CONST_DRILL" },
    { "Leaf Blower", "WORLD_HUMAN_GARDENER_LEAF_BLOWER" },
    { "Hammering", "WORLD_HUMAN_HAMMERING" },
    { "Janitor", "WORLD_HUMAN_JANITOR" },
    { "Maid", "WORLD_HUMAN_MAID_CLEAN" },
    { "Welding", "WORLD_HUMAN_WELDING" },
};

static const named_group scenario_groups[] = {
    { "Ambient", scenario_ambient, 8 },
    { "Activities", scenario_activities, 7 },
    { "Animals", scenario_animals, 6 },
    { "Fitness", scenario_fitness, 6 },
    { "Industrial", scenario_industrial, 7 },
};
static const int scenario_group_count = 5;

static const named_entry clipset_motion[] = {
    { "Businessman", "move_m@business@a" },
    { "Gangster", "move_m@gangster@generic" },
    { "Hero", "move_m@brave@a" },
    { "Hiker", "move_m@hiking" },
    { "Hobo", "move_m@hobo@a" },
    { "Injured", "move_m@injured" },
    { "Quick", "move_m@quick" },
    { "Wasted", "move_m@drunk@slightlydrunk" },
    { "Very Wasted", "move_m@drunk@verydrunk" },
};

static const named_entry clipset_weapon[] = {
    { "Bag", "missfbi4prepp1_garbageman" },
    { "Bucket", "move_ped_wpn_bucket" },
    { "Cane", "move_lester_CaneUp" },
    { "Jerry Can", "move_ped_wpn_jerrycan_generic" },
    { "Mop", "move_ped_wpn_mop" },
    { "Rifle", "Wpn_AssaultRifle_WeaponHoldingCrouched" },
    { "Sack", "MOVE_P_M_ZERO_RUCKSACK" },
};

static const named_group clipset_groups[] = {
    { "Motion", clipset_motion, 9 },
    { "Weapon", clipset_weapon, 7 },
};
static const int clipset_group_count = 2;

