#pragma once
// GENERATED by tools/gen_ped_list.py - do not edit by hand.
// 95 ped models in 7 categories.
//
// Hashes are joaat of the model name, which is build- and platform-independent,
// so these carry over from PC unchanged. Entries missing from this build are
// rejected at runtime by IS_MODEL_IN_CDIMAGE rather than filtered here.
#include <stdint.h>

struct ped_entry {
    const char* name;
    uint32_t    hash;
};

struct ped_category {
    const char*       name;
    const ped_entry*  items;
    int               count;
};

static const ped_entry ped_list_popular[] = {
    { "Alien", 0x64611296U },
    { "Astronaut", 0xE7B31432U },
    { "Playboy (Naked)", 0x4498DDEU },
    { "Hooker", 0x28ABF95U },
    { "Pogo", 0xDC59940DU },
    { "Stripper", 0x52580019U },
    { "Swat", 0x8D8F1B10U },
    { "Topless", 0x9CF26183U },
    { "Zombie", 0xAC4B4506U },
};

static const ped_entry ped_list_story[] = {
    { "Michael", 0xD7114C9U },
    { "Franklin", 0x9B22DBAFU },
    { "Trevor", 0x9B810FA2U },
    { "Amanda", 0x6D1E15F7U },
    { "Ashley", 0x7EF440DBU },
    { "Brad", 0xBDBB4922U },
    { "Chef", 0x49EADBF6U },
    { "Chris Formage", 0x286E54A7U },
    { "Clag", 0x6CCFE08AU },
    { "Cletus", 0xE6631195U },
    { "Dave Norton", 0x15CD4C33U },
    { "Denise", 0x820B33BDU },
    { "Fabien", 0xD090C350U },
    { "Floyd", 0xB1B196B2U },
    { "Jay Norris", 0x7A32EE74U },
    { "Jimmy", 0x570462B9U },
    { "Lamar", 0x65B93076U },
    { "Lazlow", 0xDFE443E5U },
    { "Lester", 0x4DA6E849U },
    { "Mrs Phillips", 0x3862EEA8U },
    { "Stretch", 0x36984358U },
    { "Tao Cheng", 0xDC5C5EA5U },
    { "Tennis Coach", 0xA23B5F57U },
    { "Tracy", 0xDE352A35U },
    { "Wade", 0x92991B72U },
};

static const ped_entry ped_list_animals[] = {
    { "Boar", 0xCE5FF074U },
    { "Chimp", 0xA8683715U },
    { "Chop", 0x14EC17EAU },
    { "Cow", 0xFCFA9E1EU },
    { "Coyote", 0x644AC75EU },
    { "Crow", 0x18012A9FU },
    { "Deer", 0xD86B5A95U },
    { "Fish", 0x2FD800B7U },
    { "Chicken Hawk", 0xAAB71F62U },
    { "Hen", 0x6AF51FAFU },
    { "Husky", 0x4E8F95A2U },
    { "Mountain Lion", 0x1250D7BAU },
    { "Pig", 0xB11BAB56U },
    { "Pigeon", 0x6A20728U },
    { "Retriever", 0x349F33E1U },
    { "Rhesus", 0xC2D06F53U },
    { "Rottweiler", 0x9563221DU },
    { "Seagull", 0xD3939DFDU },
    { "Tiger Shark", 0x6C3F072U },
    { "Shepherd", 0x431FC24CU },
};

static const ped_entry ped_list_emergency[] = {
    { "Black Ops", 0xB3F3EE34U },
    { "Chem Security", 0x2EFEAFD5U },
    { "City Cop", 0x5E3DA4A4U },
    { "County Cop", 0x9AB35F63U },
    { "Fireman", 0xB6B1EDA8U },
    { "Security Guard", 0x709220C7U },
    { "Highway Cop", 0x739B1EF5U },
    { "Lifeguard", 0xB4A6862U },
    { "Marine", 0x72C0CAD2U },
    { "Marine (Senior)", 0xF0259D83U },
    { "Paramedic", 0xB353629EU },
    { "Ranger", 0xEF7135AEU },
    { "Prison Guard", 0x56C96FC6U },
    { "Security Guard", 0xD768B228U },
    { "Sheriff", 0xB144F9B9U },
    { "Snow Cop", 0x1AE8BB58U },
};

static const ped_entry ped_list_role[] = {
    { "Bouncer", 0x9FD4292DU },
    { "Bride", 0x6162EC47U },
    { "Pest Control", 0x48114518U },
    { "Doctor", 0xD47303ACU },
    { "Factory Worker", 0x4163A158U },
    { "Garbage Man", 0xEE75A00FU },
    { "Groom", 0xFECE8B85U },
    { "Hunter", 0xCE1324DEU },
    { "Jesus", 0xCE2CB751U },
    { "Mime", 0x3CDCA742U },
    { "Priest", 0x6437E77DU },
    { "Prisoner", 0xB1BB9B59U },
    { "Scientist", 0x4117D39BU },
    { "Spy", 0x5B81D86CU },
};

static const ped_entry ped_list_ambient[] = {
    { "Body Builder", 0xDA116E7EU },
    { "Nonce", 0x7DC3908FU },
    { "Guido", 0xC6B49A2FU },
    { "Statue", 0x795AC7A8U },
    { "Mani", 0xC8BB1E52U },
    { "Griff", 0xC454BCBBU },
};

static const ped_entry ped_list_misc[] = {
    { "Dead Hooker", 0x73DEA88BU },
    { "Imporage", 0x348065F5U },
    { "Marston", 0x38430167U },
    { "Misty", 0xD128FF9DU },
    { "Niko", 0xEEDACFC9U },
};

static const ped_category ped_categories[] = {
    { "Popular", ped_list_popular, 9 },
    { "Story", ped_list_story, 25 },
    { "Animals", ped_list_animals, 20 },
    { "Emergency", ped_list_emergency, 16 },
    { "Role", ped_list_role, 14 },
    { "Ambient", ped_list_ambient, 6 },
    { "Misc", ped_list_misc, 5 },
};
static const int ped_category_count = 7;
