"""Generate src/game/vehicle_list.h from the game's own vehicles.meta files.

Source of truth is the PS4 1.57 RPF dump, i.e. every vehicle that actually exists on this
build - base game plus every DLC. Later files override earlier ones on the same modelName,
which mirrors how the game itself layers DLC content.

usage: python tools/gen_vehicle_list.py [<dump root>]
"""
import glob
import io
import os
import re
import sys
from collections import OrderedDict

DUMP = sys.argv[1] if len(sys.argv) > 1 else r"E:\Projects\IDA\PS4\GTA5\RPF\dumps"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "game", "vehicle_list.h")

# GTA V vehicle-class order, matching GET_VEHICLE_CLASS
CLASSES = [
    ("VC_COMPACT", "Compacts"), ("VC_SEDAN", "Sedans"), ("VC_SUV", "SUVs"),
    ("VC_COUPE", "Coupes"), ("VC_MUSCLE", "Muscle"), ("VC_SPORT_CLASSIC", "Sports Classics"),
    ("VC_SPORT", "Sports"), ("VC_SUPER", "Super"), ("VC_MOTORCYCLE", "Motorcycles"),
    ("VC_OFF_ROAD", "Off-road"), ("VC_INDUSTRIAL", "Industrial"), ("VC_UTILITY", "Utility"),
    ("VC_VAN", "Vans"), ("VC_CYCLE", "Cycles"), ("VC_BOAT", "Boats"),
    ("VC_HELICOPTER", "Helicopters"), ("VC_PLANE", "Planes"), ("VC_SERVICE", "Service"),
    ("VC_EMERGENCY", "Emergency"), ("VC_MILITARY", "Military"), ("VC_COMMERCIAL", "Commercial"),
    ("VC_RAIL", "Trains"), ("VC_OPENWHEEL", "Open Wheel"),
]
CLASS_IDX = {name: i for i, (name, _) in enumerate(CLASSES)}
# the meta files are not consistent about these two spellings
CLASS_IDX["VC_COMPACTS"] = CLASS_IDX["VC_COMPACT"]
CLASS_IDX["VC_OPEN_WHEEL"] = CLASS_IDX["VC_OPENWHEEL"]

def tag(block, name):
    m = re.search(r"<%s>([^<]*)</%s>" % (name, name), block)
    return m.group(1).strip() if m else ""


def main():
    files = sorted(glob.glob(os.path.join(DUMP, "**", "vehicles.meta"), recursive=True))
    if not files:
        sys.exit("no vehicles.meta found under %s" % DUMP)

    # <Item> elements nest (door lists, vfx samples, ...), so splitting on them loses
    # entries. modelName is the first field of every vehicle, so splitting there gives
    # exactly one chunk per vehicle regardless of nesting.
    vehicles = OrderedDict()
    unknown = {}
    for path in files:
        text = io.open(path, encoding="utf-8", errors="replace").read()
        for chunk in text.split("<modelName>")[1:]:
            end = chunk.find("</modelName>")
            if end < 0:
                continue
            model = chunk[:end].strip().lower()
            if not model or model == "null":
                continue
            cls = tag(chunk, "vehicleClass")
            if cls not in CLASS_IDX:
                unknown[cls] = unknown.get(cls, 0) + 1
                continue
            make = tag(chunk, "vehicleMakeName")
            vehicles[model] = {
                "model": model,
                # no GXT label lookup is available in the payload, so the display
                # name is the model name title-cased - unambiguous and it is what
                # you would type anyway.
                "name": model[:1].upper() + model[1:],
                "make": "" if make.lower() in ("", "null") else make.title(),
                "cls": CLASS_IDX[cls],
            }
    if unknown:
        print("skipped, unknown vehicleClass:", unknown)

    rows = sorted(vehicles.values(), key=lambda v: (v["cls"], v["model"]))
    per_class = [0] * len(CLASSES)
    for v in rows:
        per_class[v["cls"]] += 1

    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("#pragma once\n")
        f.write("// GENERATED by tools/gen_vehicle_list.py - do not edit by hand.\n")
        f.write("// Extracted from the PS4 1.57 vehicles.meta set (%d files, base game + DLC),\n" % len(files))
        f.write("// so this is exactly the set of vehicles this build can spawn.\n")
        f.write("#include <stdint.h>\n\n")
        f.write("struct vehicle_entry {\n")
        f.write("    const char* model;   // spawn name, hashed with get_hash_key\n")
        f.write("    const char* name;    // display name\n")
        f.write('    const char* make;    // manufacturer, "" when the meta has none\n')
        f.write("    uint8_t     cls;     // index into vehicle_class_names\n")
        f.write("};\n\n")
        f.write("static const char* const vehicle_class_names[] = {\n")
        for _, disp in CLASSES:
            f.write('    "%s",\n' % disp)
        f.write("};\n")
        f.write("static const int vehicle_class_count = %d;\n\n" % len(CLASSES))
        f.write("static const vehicle_entry vehicle_list[] = {\n")
        cur = -1
        for v in rows:
            if v["cls"] != cur:
                cur = v["cls"]
                f.write("    // ---- %s (%d)\n" % (CLASSES[cur][1], per_class[cur]))
            f.write('    { "%s", "%s", "%s", %d },\n' % (v["model"], v["name"], v["make"], v["cls"]))
        f.write("};\n")
        f.write("static const int vehicle_list_count = %d;\n" % len(rows))

    print("files parsed : %d" % len(files))
    print("vehicles     : %d" % len(rows))
    for i, (_, disp) in enumerate(CLASSES):
        if per_class[i]:
            print("   %-16s %d" % (disp, per_class[i]))
    print("written      : %s" % os.path.normpath(OUT))


main()
