"""Generate src/rage/invoker/natives_hash.h from a hash-based GTA V natives header.

The RVA-based natives.h covers 2,840 natives; the build registers ~6,700. The rest
exist in the eboot but never made it into that header, which quietly limits every
feature. This fills the gap from the other side: a hash-based header supplies the
names and signatures, and the natives are called through the hash table recovered
from the game's own registry at runtime (rage::hash_natives).

Only natives MISSING from natives.h are emitted, into the same `native` namespace,
so feature code calls native::whatever(...) without caring which mechanism backs
it. The one behavioural difference is timing: RVA natives work from the first
frame, hash natives only once the registry has been read (a few seconds in).

The source header must be the one whose invoke<> hashes are THIS build's. Public
databases (FiveM, NativeDB) key on the 2013 b323 hash instead, which is what such
headers carry in the trailing comment - those will not resolve at runtime.

usage: python tools/gen_hash_natives.py [<source natives.h>]
"""
import io
import os
import re
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\BBC\Desktop\natives.h"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "rage", "invoker", "natives_hash.h")
EXISTING = [os.path.join(HERE, "..", "src", "rage", "invoker", "natives.h"),
            os.path.join(HERE, "..", "src", "rage", "invoker", "missing_natives.h")]

# Types the project spells differently, plus the two it has no typedef for.
TYPE_MAP = {
    "void": "Void",
    "BOOL": "bool",
    "Vector3": "math::vector3<float>",
    "FireId": "int",
    "Interior": "int",
}

DECL = re.compile(
    r"static\s+([A-Za-z_][A-Za-z0-9_]*\s*\**)\s+([A-Z][A-Z0-9_]*)\s*\((.*?)\)\s*\{\s*"
    r"(?:return\s+)?invoke\s*<[^>]*>\s*\(\s*(0x[0-9A-Fa-f]{16})\s*(.*?)\)\s*;\s*\}"
)


def map_type(t):
    t = t.strip()
    stars = ""
    while t.endswith("*"):
        stars += "*"
        t = t[:-1].strip()
    const = ""
    if t.startswith("const "):
        const = "const "
        t = t[6:].strip()
    return const + TYPE_MAP.get(t, t) + stars


def split_params(params):
    """-> (rendered declaration, [argument names]); None if anything is unnamed."""
    params = params.strip()
    if not params or params == "void":
        return "", []
    out, names = [], []
    for p in params.split(","):
        p = p.strip()
        if not p:
            return None
        m = re.match(r"^(.*?)([A-Za-z_][A-Za-z0-9_]*)$", p)
        if not m:
            return None
        type_part, name = m.group(1).strip(), m.group(2)
        if not type_part:            # a bare identifier is a type without a name
            return None
        out.append("%s %s" % (map_type(type_part), name))
        names.append(name)
    return ", ".join(out), names


def main():
    src = io.open(SRC, encoding="utf-8", errors="replace").read()

    # Take the identifier immediately before the parameter list, per line. A
    # return type can contain spaces (const char*, math::vector3<float>), so
    # anchoring on "static <one token> <name>(" silently misses those and emits
    # duplicates that differ only in return type - which does not compile.
    have = set()
    for path in EXISTING:
      for line in io.open(path, encoding="utf-8", errors="replace"):
        if "static" not in line:
            continue
        m = re.search(r"\b([a-z_][a-z0-9_]*)\s*\(", line)
        if m:
            have.add(m.group(1))

    rows, skipped, dup = [], 0, 0
    for m in DECL.finditer(src):
        ret, name, params, hash_, _ = m.groups()
        lower = name.lower()
        if lower in have:
            dup += 1
            continue
        parsed = split_params(params)
        if parsed is None:
            skipped += 1
            continue
        decl, names = parsed
        args = "".join(", " + n for n in names)
        rows.append((lower, map_type(ret), decl, hash_, args))
        have.add(lower)

    rows.sort()

    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("#pragma once\n")
        f.write("// GENERATED by tools/gen_hash_natives.py - do not edit by hand.\n")
        f.write("//\n")
        f.write("// The natives this build registers that natives.h does not cover (%d of them).\n" % len(rows))
        f.write("// Called by hash through the registry recovered at runtime, so unlike the RVA\n")
        f.write("// header these only work once rage::hash_natives::usable() is true - a few\n")
        f.write("// seconds into the game. Until then they return a default-constructed value\n")
        f.write("// rather than calling anything.\n")
        f.write("//\n")
        f.write("// Hashes are this build's own, taken from the registry, NOT the b323 hashes the\n")
        f.write("// public native databases use.\n")
        f.write("#include \"rage/invoker/hash_natives.h\"\n")
        f.write("#include \"rage/types/base_types.h\"\n")
        f.write("#define _ih rage::hash_natives::invoke_hash\n\n")
        f.write("namespace native {\n\n")
        for lower, ret, decl, hash_, args in rows:
            f.write("\tstatic %s %s(%s) { return _ih<%s>(%sULL%s); }\n"
                    % (ret, lower, decl, ret, hash_, args))
        f.write("\n}\n")

    print("source            : %s" % SRC)
    print("already in RVA hdr: %d (skipped)" % dup)
    print("unparsable        : %d" % skipped)
    print("emitted           : %d" % len(rows))
    print("written           : %s" % os.path.normpath(OUT))


main()
