"""Generate src/game/ped_list.h from Ozark's ped-model lists.

Ped model hashes are joaat of the model name, so unlike native hashes they are the
same on every build and platform - Ozark's PC lists work unchanged on PS4. That is
why these are lifted wholesale rather than extracted from the RPF dump: the dump's
meta files do not carry a model list at all (the models live as assets inside the
archives), and a curated, categorised list is more useful in a menu anyway.

Anything that is not actually present in this build is filtered out at runtime with
IS_MODEL_IN_CDIMAGE, so a PC-only entry simply reports "not available" instead of
being spawned.

usage: python tools/gen_ped_list.py [<ozark lists.cpp>]
"""
import io
import os
import re
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else \
    r"C:\Users\BBC\Desktop\GTA\GTA5Menus-main\ozark\GTAV\src\global\lists.cpp"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "game", "ped_list.h")

# The categories Ozark splits its Model menu into, in menu order.
CATEGORIES = [
    ("g_ped_model_popular",   "Popular"),
    ("g_ped_model_story",     "Story"),
    ("g_ped_model_animal",    "Animals"),
    ("g_ped_model_emergency", "Emergency"),
    ("g_ped_model_role",      "Role"),
    ("g_ped_model_ambient",   "Ambient"),
    ("g_ped_model_misc",      "Misc"),
]

ENTRY = re.compile(r'\{\s*localization\(\s*"([^"]+)"[^)]*\)\s*,\s*(0[xX][0-9A-Fa-f]+)\s*\}')


def main():
    src = io.open(SRC, encoding="utf-8", errors="replace").read()

    cats = []
    total = 0
    for var, label in CATEGORIES:
        m = re.search(re.escape(var) + r"\[\]\s*=\s*\{(.*?)\n\s*\};", src, re.S)
        if not m:
            print("missing: %s" % var)
            continue
        rows = ENTRY.findall(m.group(1))
        cats.append((label, rows))
        total += len(rows)

    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("#pragma once\n")
        f.write("// GENERATED by tools/gen_ped_list.py - do not edit by hand.\n")
        f.write("// %d ped models in %d categories.\n" % (total, len(cats)))
        f.write("//\n")
        f.write("// Hashes are joaat of the model name, which is build- and platform-independent,\n")
        f.write("// so these carry over from PC unchanged. Entries missing from this build are\n")
        f.write("// rejected at runtime by IS_MODEL_IN_CDIMAGE rather than filtered here.\n")
        f.write("#include <stdint.h>\n\n")
        f.write("struct ped_entry {\n")
        f.write("    const char* name;\n")
        f.write("    uint32_t    hash;\n")
        f.write("};\n\n")
        f.write("struct ped_category {\n")
        f.write("    const char*       name;\n")
        f.write("    const ped_entry*  items;\n")
        f.write("    int               count;\n")
        f.write("};\n\n")

        for label, rows in cats:
            ident = label.lower().replace(" ", "_")
            f.write("static const ped_entry ped_list_%s[] = {\n" % ident)
            for name, hash_ in rows:
                f.write('    { "%s", %sU },\n' % (name.replace('"', ''), hash_))
            f.write("};\n\n")

        f.write("static const ped_category ped_categories[] = {\n")
        for label, rows in cats:
            ident = label.lower().replace(" ", "_")
            f.write('    { "%s", ped_list_%s, %d },\n' % (label, ident, len(rows)))
        f.write("};\n")
        f.write("static const int ped_category_count = %d;\n" % len(cats))

    print("source     : %s" % SRC)
    for label, rows in cats:
        print("  %-12s %d" % (label, len(rows)))
    print("total      : %d" % total)
    print("written    : %s" % os.path.normpath(OUT))


main()
