"""Generate src/game/anim_list.h from Ozark's animation, scenario and clipset lists.

Like the ped models, these are plain asset names - anim dictionaries, scenario ids
and clipset names - so they are build- and platform-independent and port from PC
unchanged. Only the native used to play them differs, and that is handled in the
menu code rather than here.

Ozark keeps the lists inline in its animation submenus rather than in lists.cpp,
so each file is scanned individually.

usage: python tools/gen_anim_list.py [<ozark animation dir>]
"""
import io
import os
import re
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else \
    r"C:\Users\BBC\Desktop\GTA\GTA5Menus-main\ozark\GTAV\src\menu\base\submenus\main\player\animation"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "game", "anim_list.h")

# Entries look like { localization("Label", true), "dict", "anim" } for animations
# and { localization("Label", true), "id" } for scenarios and clipsets.
# The animation lists wrap the pair in its own braces:
#   { localization("X", true), { "dict", "anim" } }
ENTRY_2 = re.compile(r'\{\s*localization\(\s*"([^"]+)"[^)]*\)\s*,\s*\{?\s*"([^"]*)"\s*,\s*"([^"]*)"\s*\}?\s*\}')
ENTRY_1 = re.compile(r'\{\s*localization\(\s*"([^"]+)"[^)]*\)\s*,\s*"([^"]*)"\s*\}')
# The element type can itself contain angle brackets
# (scroll_struct<std::pair<const char*, const char*>>), so match to the last '>'
# on the declaration line rather than the first.
LIST = re.compile(r'scroll_struct<[^\n]*>\s+(\w+)\s*\[\]\s*=\s*\{(.*?)\n\s*\};', re.S)


def scan(path):
    """-> [(list name, [(label, a, b)])] with b empty for single-string entries."""
    if not os.path.exists(path):
        return []
    s = io.open(path, encoding="utf-8", errors="replace").read()
    out = []
    for name, body in LIST.findall(s):
        rows = [(l, a, b) for l, a, b in ENTRY_2.findall(body)]
        if not rows:
            rows = [(l, a, "") for l, a in ENTRY_1.findall(body)]
        if rows:
            out.append((name, rows))
    return out


def emit(f, struct, ident, rows, two):
    f.write("static const %s %s[] = {\n" % (struct, ident))
    for label, a, b in rows:
        if two:
            f.write('    { "%s", "%s", "%s" },\n' % (label, a, b))
        else:
            f.write('    { "%s", "%s" },\n' % (label, a))
    f.write("};\n\n")


def main():
    anims = scan(os.path.join(SRC, "animations.cpp"))
    scens = scan(os.path.join(SRC, "scenario.cpp"))
    clips = scan(os.path.join(SRC, "clipsets.cpp"))

    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("#pragma once\n")
        f.write("// GENERATED by tools/gen_anim_list.py - do not edit by hand.\n")
        f.write("//\n")
        f.write("// Asset names, so these are the same on every build and platform. An entry the\n")
        f.write("// build does not have simply fails to stream and the animation does not play.\n\n")

        f.write("struct anim_entry  { const char* name; const char* dict; const char* anim; };\n")
        f.write("struct named_entry { const char* name; const char* id; };\n")
        f.write("struct anim_group  { const char* name; const anim_entry*  items; int count; };\n")
        f.write("struct named_group { const char* name; const named_entry* items; int count; };\n\n")

        def block(sets, struct, prefix, two, group_struct):
            groups = []
            for name, rows in sets:
                ident = prefix + "_" + re.sub(r"^g_", "", name)
                emit(f, struct, ident, rows, two)
                label = re.sub(r"^g_\w*?_", "", name).replace("_", " ").title()
                groups.append((label, ident, len(rows)))
            f.write("static const %s %s_groups[] = {\n" % (group_struct, prefix))
            for label, ident, n in groups:
                f.write('    { "%s", %s, %d },\n' % (label, ident, n))
            f.write("};\n")
            f.write("static const int %s_group_count = %d;\n\n" % (prefix, len(groups)))
            return sum(n for _, _, n in groups)

        na = block(anims, "anim_entry",  "animation", True,  "anim_group")
        ns = block(scens, "named_entry", "scenario",  False, "named_group")
        nc = block(clips, "named_entry", "clipset",   False, "named_group")

    print("animations : %d in %d groups" % (na, len(anims)))
    print("scenarios  : %d in %d groups" % (ns, len(scens)))
    print("clipsets   : %d in %d groups" % (nc, len(clips)))
    print("written    : %s" % os.path.normpath(OUT))


main()
