#include <stdio.h>
#include <string.h>
#include <stddef.h>

#include <GoldHEN/Common.h>

#define PLUGIN_NAME    "InsulinGTAV"
#define PLUGIN_VERSION "1.00"

// GoldHEN reads these to list the plugin.
#define attr_public __attribute__((visibility("default")))

attr_public const char *g_pluginName    = PLUGIN_NAME;
attr_public const char *g_pluginDesc    = "Generated by OrbisForge";
attr_public const char *g_pluginAuth    = "unknown";
attr_public const char *g_pluginVersion = PLUGIN_VERSION;

// This is compiled as C++, so the entry points need C linkage: crtprx.o's
// _init resolves module_start/module_stop by their unmangled names.
extern "C" {

static void notify(const char *msg)
{
    OrbisNotificationRequest req;

    memset(&req, 0, sizeof(req));

    req.type            = NotificationRequest;
    req.targetId        = -1;
    req.useIconImageUri = 1;

    strncpy(req.iconUri, "cxml://psnotification/tex_icon_system", sizeof(req.iconUri) - 1);
    strncpy(req.message, msg, sizeof(req.message) - 1);

    // Non-blocking: module_start must not stall the title's startup.
    sceKernelSendNotificationRequest(0, &req, sizeof(req), 0);
}

int module_start(size_t argc, const void *argp)
{
    (void)argc;
    (void)argp;

    notify(PLUGIN_NAME " v" PLUGIN_VERSION " loaded");

    return 0;
}

int module_stop(size_t argc, const void *argp)
{
    (void)argc;
    (void)argp;

    notify(PLUGIN_NAME " unloaded");

    return 0;
}

}